<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 10/12/2017
 * Time: 5:58 PM
 */

namespace amintado\pay;


use Yii;
use yii\helpers\ArrayHelper;

class Module extends \yii\base\Module
{
    public $api='';
    public $controllerNamespace='amintado\pay\controllers';


    public function init()
    {
        $this->initI18N();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * TranslationTrait manages methods for all translations used in Krajee extensions
     *
     * @property array $i18n
     *
     * @author Kartik Visweswaran <kartikv2@gmail.com>
     * @since 1.8.8
     * Yii i18n messages configuration for generating translations
     * source : https://github.com/kartik-v/yii2-krajee-base/blob/master/TranslationTrait.php
     * Edited by : Yohanes Candrajaya <moo.tensai@gmail.com>
     *
     *
     * @return void
     */
    public function initI18N()
    {
        $reflector = new \ReflectionClass(get_class($this));
        $dir = dirname($reflector->getFileName());

        Yii::setAlias("@atpay", $dir);
        $config = [
            'class' => 'yii\i18n\PhpMessageSource',
            'basePath' => "@atpay/messages",
            'forceTranslation' => true
        ];
        $globalConfig = ArrayHelper::getValue(Yii::$app->i18n->translations, "atpay*", []);
        if (!empty($globalConfig)) {
            $config = array_merge($config, is_array($globalConfig) ? $globalConfig : (array)$globalConfig);
        }
        Yii::$app->i18n->translations["atpay*"] = $config;
    }
}