<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 10/18/2017
 * Time: 10:11 AM
 */

namespace amintado\pay\widgets;


use yii\base\Widget;

class PaymentsettingsWidget extends Widget
{

    public function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
        echo $this->render('@vendor/amintado/yii2-module-pay/views/widgets/settings.php');
    }
}