<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 10/19/2017
 * Time: 12:43 AM
 */

namespace amintado\pay\widgets;


use amintado\pay\classes\Atpayfunctions;
use common\models\UserInfo;
use yii\base\Widget;


class PaymentDetailsWidget extends Widget
{

    public function init()
    {
        Atpayfunctions::InitModule();
        parent::init(); // TODO: Change the autogenerated stub
        $sumAmounts = Atpayfunctions::Amount(UserInfo::find()->select('balance')->asArray()->sum('balance'));
        $CountZeroUsers = UserInfo::find()->select('balance')->where(['balance' => 0])->count();
        $allUsers = UserInfo::find()->select('id')->count();
        $rationZeroUsersToAll = (100 * $CountZeroUsers) / $allUsers;
        echo $this->render
        ('@vendor/amintado/yii2-module-pay/views/widgets/PaymentDetailsWidget.php',
            [
                'sumAmounts'=>$sumAmounts,
                'CountZeroUsers'=>$CountZeroUsers,
                'allUsers'=>$allUsers,
                'rationZeroUsersToAll'=>$rationZeroUsersToAll
            ]
        );
    }
}