<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 10/18/2017
 * Time: 11:21 PM
 */

namespace amintado\pay\widgets;

use common\models\UserInfo;
use Yii;
use amintado\pay\models\TransactionSearch;
use yii\base\Widget;
use amintado\pay\Module;
use common\models\User;
class PaymentTransactionsWidget extends Widget
{
    public $UserID='';
        public function init()
        {
            $moduleID = '';

            foreach (Yii::$app->modules as $key => $value) {
                if (!empty($value['class'])) {
                    if ($value['class'] == 'amintado\pay\Module') {

                        $moduleID = $key;
                        break;
                    }
                }

            }

            //---------------- init Module -------------------
            $module = (new Module($moduleID))->init();
            parent::init(); // TODO: Change the autogenerated stub
            $searchModel = new TransactionSearch();
            $dataProvider = $searchModel->search($this->UserID);
            if (empty($this->UserID)){
                $user=UserInfo::findOne(['uid'=>Yii::$app->user->id]);
            }else{
                $user=UserInfo::findOne(['uid'=>$this->UserID]);
                if (empty($this->UserID)){
                    throw new BadRequestHttpException(Yii::t('atpay', 'this user not exist'));
                }
            }

            echo $this->render('@vendor/amintado/yii2-module-pay/views/default/index.php', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'user'=>$user
            ]);
        }
}