<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'لغو',
    'Confirmation' => '',
    'Information' => '',
    'Ok' => '',

    'ID'=>'شناسه',
    'Name'=>'نام',
    'Description'=>'توضیحات',
    'Pay Price'=>'واریزی/برداشتی',
    'Deposit {amount} Rials online from card {cardnumber} in {date}'=>
    'واریز آنلاین به حساب سایت در تاریخ {date} از طریق واسط بانکی pay.ir به مبلغ {amount} از کارت بانکی {cardnumber}',
    'Deposit Online'=>'واریز به حساب',
    'Invoice Not Saved'=>'متاسفانه فاکتور ذخیره نشد',
    'Transaction Not Saved'=>'متاسفانه تراکنش شما در سیستم ثبت نشد.لطفا با مدیر سایت تماس بگیرید.',
    'User Info Not Saved'=>'تراکنش به حساب شما منظور شد، اما در فرایند افزایش موجودی به حساب شما مشکلی پیش آمد.لطفا با پشتیبانی سایت تماس بگیرید.',
    'RIAL'=>'ریال',
    'Date'=>'زمان',
    'Export All Data'=>'خروجی از همه ی داده ها',
    'Full'=>'کامل',
    'Increase in inventory'=>'افزایش موجودی',
    'Transactions'=>'تراکنش های مالی',
    'Current inventory'=>'موجودی فعلی',
    'Pay'=>'پرداخت',
    'Deposits'=>'مبلغ واریزی به ریال',
    'sum'=>'جمع',
    'Deposits'=>'واریز',
    'Removal'=>'برداشت',
    'Inventory'=>'موجودی',
    'payment settings'=>'تنظیمات سیستم پرداخت',
    'here you can edit payment module settings'=>'در اینجا شما میتوانید تنظیمات مربوط به سیستم پرداخت و درگاه بانکی، و روش های پرداختی را انجام دهید',
    'submit settings'=>'<span class="glyphicon glyphicon-floppy-disk"></span> '.'ذخیره ی تنظیمات سیستم پرداخت',
    'factor logo'=>'لوگوی فاکتورها',
    'transaction PDF'=>'فایل تراکنش',
    'Transaction receipt'=>'رسید تراکنش مالی',
    'Invoice called:'=>'صورتحساب به نام:',
    'Date:'=>'تاریخ :',
    'username:'=>'نام کاربری:',
    'Transaction Number:'=>'شماره تراکنش:',
    'address'=>'آدرس',
    'This address is included in invoices and invoice receipts'=>'این آدرس در فاکتورها و رسیدهای صورتحساب درج میشود',
    'This telephone is included in invoices and invoice receipts'=>'این شماره تلفن در فاکتور ها و صورت حساب های کاربر نمایش داده میشود.',
    'telephone'=>'شماره تماس:',
    'telephone:'=>'تلفن:',
    'One transaction:'=>'یک تراکنش انجام شده بابت:',
    'amount(rial)'=>'مبلغ(ریال)',
    'Private key for pay.ir payment'=>'کلید خصوصی درگاه Pay.ir(اگر استفاده میکنید)',
    'payIR_API'=>'کلید pay.ir',
    'this user not exist'=>'این کاربر وجود ندارد',
    'Total inventory of users'=>'جمع موجودی کاربران',
    'Number of users with inventory 0'=>'تعداد کاربران با موجودی 0',
    'Percentage of users without inventory to the total'=>'کاربران بدون موجودی به کل',
    '{percent} of users do not have inventory'=>'{percent} از کاربران موجودی ندارند'

];
